apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockflow-backend
  namespace: stockflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: stockflow-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: stockflow-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: stockflow-secrets
                  key: JWT_SECRET
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: stockflow-secrets
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: stockflow-secrets
                  key: SMTP_PASS
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stockflow-secrets
                  key: STRIPE_SECRET_KEY
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: stockflow-backend
  namespace: stockflow
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
