apiVersion: v1
kind: ConfigMap
metadata:
  name: stockflow-config
  namespace: stockflow
data:
  PORT: "5000"
  MONGODB_URI: "mongodb://stockflow-mongodb:27017/stockflow"
  REDIS_URL: "redis://stockflow-redis:6379"
  SMTP_HOST: "sandbox.smtp.mailtrap.io"
  SMTP_PORT: "2525"
  EMAIL_FROM: "alerts@stockflow.com"
