apiVersion: v1
kind: Secret
metadata:
  name: stockflow-secrets
  namespace: stockflow
type: Opaque
stringData:
  JWT_SECRET: "supersecretstockflowkey123!"
  SMTP_USER: "mockuser"
  SMTP_PASS: "mockpass"
  STRIPE_SECRET_KEY: "sk_test_mockkey12345"
